name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get package version
        id: pkg
        run: echo "VERSION=$(node -p 'require("./package.json").version')" >> "$GITHUB_ENV"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${VERSION}" >/dev/null 2>&1; then
            echo "Tag v${VERSION} already exists."
            echo "EXISTS=true" >> "$GITHUB_ENV"
          else
            echo "EXISTS=false" >> "$GITHUB_ENV"
          fi

      - name: Create tag
        if: env.EXISTS == 'false'
        run: |
          git tag v${VERSION}
          git push origin v${VERSION}
