name: Create Tag

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if version changed
        id: check_version
        run: |
          # Get the current version
          CURRENT_VERSION=$(node -p 'require("./package.json").version')
          
          # Get the previous version from the last commit
          git checkout HEAD^ package.json || true
          PREVIOUS_VERSION=$(node -p 'require("./package.json").version' || echo "none")
          git checkout HEAD package.json
          
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
            echo "VERSION_CHANGED=true" >> "$GITHUB_ENV"
          else
            echo "No version change detected"
            echo "VERSION_CHANGED=false" >> "$GITHUB_ENV"
          fi

      - name: Check if tag exists
        if: env.VERSION_CHANGED == 'true'
        id: check_tag
        run: |
          if git rev-parse "v${CURRENT_VERSION}" >/dev/null 2>&1; then
            echo "Tag v${CURRENT_VERSION} already exists."
            echo "EXISTS=true" >> "$GITHUB_ENV"
          else
            echo "EXISTS=false" >> "$GITHUB_ENV"
          fi

      - name: Create tag
        if: env.VERSION_CHANGED == 'true' && env.EXISTS == 'false'
        run: |
          git tag v${CURRENT_VERSION}
          git push origin v${CURRENT_VERSION}
