name: Manual Create Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag (e.g., 1.0.0)'
        required: true
        type: string

permissions:
  contents: write
#   packages: write
#   pull-requests: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check if tag exists
        id: check_tag
        run: |
          if git rev-parse "v${{ github.event.inputs.version }}" >/dev/null 2>&1; then
            echo "Tag v${{ github.event.inputs.version }} already exists."
            echo "EXISTS=true" >> "$GITHUB_ENV"
          else
            echo "EXISTS=false" >> "$GITHUB_ENV"
          fi

      - name: Create tag
        if: env.EXISTS == 'false'
        run: |
          git tag v${{ github.event.inputs.version }}
          git push origin v${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag already exists
        if: env.EXISTS == 'true'
        run: |
          echo "Tag v${{ github.event.inputs.version }} already exists. No action taken." 